/*----------------------------------------------------------------------------
 *      
 *----------------------------------------------------------------------------
 *      Name:    BUTTONS.H
 *      Purpose: Microprocessors Laboratory
 *----------------------------------------------------------------------------
 *      
 *      Author: Pawel Russek AGH University of Science and Technology
 *---------------------------------------------------------------------------*/

#include "MKL05Z4.h"                    /* Device header */
#include "buttons.h"
#include "fsm.h"

/* Buttons connected to port B */
typedef enum{ BUT1 = 1, BUT2 = 2, BUT3 = 3} ButtonType;

/*Number of IRQ generated by PORTC_PORTD interrupt*/
static const IRQn_Type myPORT_IRQn = 31; /* -1 is not a correct value */ /* ToDo 5.1: Define interrupt (IRQ) number for PORTB. Check MKL05Z4 or find in NVIC section of KL05 Sub-Family Reference Manual - NVIC section */ 


/*----------------------------------------------------------------------------
	Interrupt service routine
	Button will cause PORTC_PORTD interrupt 
 *----------------------------------------------------------------------------*/

void PORTB_IRQHandler(void){		/* ToDo 5.2: Put a proper name of PORTB Interrupt service routine ISR. See system_MKL05Z4.s file for function name */ 

	if( PORTB->ISFR & (1 << BUT1) ){        /* Check in ISFR register if button BUT1 is pressed */
		fsmFastSlow();
    while((FPTB->PDIR&(1<<BUT1))==0);				/* ToDo 7.1: Enable wait in the interrupt for SW1 button release */	
		PORTB->PCR[BUT1] |= PORT_PCR_ISF_MASK; /* ToDo 5.3: Make sure that interrupt service flag (ISF) in Port Control Register is cleared during ISR execution */
  }
	
	if( PORTB->ISFR & (1 << BUT2) ){          /* Check in ISFR register if button BUT2 is pressed */
		fsmStartStop();
    while((FPTB->PDIR&(1<<BUT2))==0);				/* ToDo 7.1: Enable wait in the interrupt for SW2 button release */	
		PORTB->PCR[BUT2] |= PORT_PCR_ISF_MASK; /* ToDo 5.3: Make sure that interrupt service flag (ISF) in Port Control Register is cleared during ISR execution */

  }
	if(PORTB->ISFR & (1 << BUT3) ) {
		fsmReset();
		while((FPTB->PDIR&(1<<BUT3))==0);				/* ToDo 7.1: Enable wait in the interrupt for SW2 button release */	
		PORTB->PCR[BUT3] |= PORT_PCR_ISF_MASK;
	}
}



/*----------------------------------------------------------------------------
	Function initializes port C pin for switch 1 (SW1) handling
	and enables PORT_C_D interrupts
 *----------------------------------------------------------------------------*/
void buttonsInitialize(void){
	SIM->SCGC5 |=  SIM_SCGC5_PORTB_MASK; 				/* Enable clock for port B */
	PORTB->PCR[BUT1] |= PORT_PCR_MUX(1);      	/* Pin PTB0 is GPIO */
	PORTB->PCR[BUT2] |= PORT_PCR_MUX(1);      	/* Pin PTB1 is GPIO */
	PORTB->PCR[BUT3] |= PORT_PCR_MUX(1);
	/* Port control register for bit 3 of port C configuration. Activate pull up and interrupt */
	PORTB->PCR[BUT1] |=  PORT_PCR_PE_MASK |		/* ToDo 5.4: Set PE bit in PCR register to enable pull resistor. See KL05 Sub-Family Reference Manual */
													PORT_PCR_PS_MASK;	/* ToDo 5.5: Set PS bit in PCR register to select pull up. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT1] |=  PORT_PCR_IRQC(9);		/* ToDo 5.6: Set value for IRQC bit field in PCR register to select rising edge interrupts for PORTB. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT2] |=  PORT_PCR_PE_MASK |		/* ToDo 5.4: Set PE bit in PCR register to enable pull resistor. See KL05 Sub-Family Reference Manual */
											 PORT_PCR_PS_MASK;			/* ToDo 5.5: Set PS bit in PCR register to select pull up. See KL405 Sub-Family Reference Manual */
	PORTB->PCR[BUT2] |=  PORT_PCR_IRQC(9);	  /* ToDo 5.6: Set value for IRQC bit field in PCR register to select falling edge interrupts for PORTB. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT3] |=  PORT_PCR_PE_MASK |		/* ToDo 5.4: Set PE bit in PCR register to enable pull resistor. See KL05 Sub-Family Reference Manual */
													PORT_PCR_PS_MASK;	/* ToDo 5.5: Set PS bit in PCR register to select pull up. See KL05 Sub-Family Reference Manual */
	PORTB->PCR[BUT3] |=  PORT_PCR_IRQC(9);
		
	/* ARM's Nested Vector Interrupt Controller configuration */
	NVIC_ClearPendingIRQ(myPORT_IRQn);				/* Clear NVIC any pending interrupts on PORTC_B */
	NVIC_EnableIRQ(myPORT_IRQn);							/* Enable NVIC interrupts source for PORTC_B module */
	
	NVIC_SetPriority (myPORT_IRQn, 3);			/* ToDo 7.2a: Set POR_B interrupt priority level  */ 

}



